#!/bin/bash

source env

## create create_guild voting app acl
dao acl create $DAO_ADDRESS $CREATE_GUILD_VOTING_APP_ADDRESS CREATE_VOTES_ROLE 0xffffffffffffffffffffffffffffffffffffffff $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl create $DAO_ADDRESS $CREATE_GUILD_AGENT_ADDRESS EXECUTE_ROLE $CREATE_GUILD_VOTING_APP_ADDRESS $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl create $DAO_ADDRESS $CREATE_GUILD_VOTING_APP_ADDRESS MODIFY_SUPPORT_ROLE $OWNERSHIP_VOTING_APP_ADDRESS $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl create $DAO_ADDRESS $CREATE_GUILD_VOTING_APP_ADDRESS MODIFY_QUORUM_ROLE $OWNERSHIP_VOTING_APP_ADDRESS $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl create $DAO_ADDRESS $CREATE_GUILD_VOTING_APP_ADDRESS SET_MIN_GUILD_BALANCE_ROLE $OWNERSHIP_VOTING_APP_ADDRESS $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl create $DAO_ADDRESS $CREATE_GUILD_VOTING_APP_ADDRESS SET_MIN_TIME_ROLE $OWNERSHIP_VOTING_APP_ADDRESS $OWNERSHIP_VOTING_APP_ADDRESS --env $DEPLOY_ENV

dao acl view $DAO_ADDRESS --env $DEPLOY_ENV
